name: build and publish docker image and crate

on:
  push:
    branches:
      - *

env:
  CARGO_API_KEY: ${{secrets.CARGO_API_KEY}}

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - 
        name: Generate build number
        uses: einaregilsson/build-number@v3
        with:
          token: ${{secrets.github_token}} 

      - 
        name: Read file contents
        id: read_file
        uses: andstor/file-reader-action@v1
        with:
          path: "VERSION"

      -
        name: Build docker image and push dev
        uses: docker/build-push-action@v3
        with:
          push: true
          file: Dockerfile.dev
          tags: willettisaak/crabby_trade:${{steps.read_file.outputs.contents}}.${{env.BUILD_NUMBER}}