name: ci

on:
  push:
  pull_request:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  run-tests:
    uses: crabby_trade/crabby_trade/.github/workflows/build.yml@main
    steps:
      - name: run tests
        run: make run-tests
