name: ci

on:
  push:
    branches: 
  pull_request:
    branches: [main]

jobs:
  run-tests:

    runs-on: rust
    
    steps:
      
      - name: checkout
        uses: checkout@v3

      - name: run tests
        run: cargo test
