name: ci

on:
  push:
  pull_request:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  run-tests:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - 
        name: get build essentials
        run: |
          apt-get update 
          apt-get install build-essential
      - 
        name: run tests
        run: Make run-tests
