name: ci

on:
  push:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  run-tests:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - 
        name: Check out repo
        uses: actions/checkout@v3
      - 
        name: Read file contents
        id: read_file
        uses: andstor/file-reader-action@v1
        with:
          path: "VERSION"
      - 
        name: run tests
        run: make run-tests
