name: ci

on:
  push:
  pull_request:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  run-tests:
    runs-on: rust
    steps:
      - name: checkout
        uses: checkout@v3

      - name: run tests
        run: cargo test
