name: ci

on:
  push:
  pull_request:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  run-tests:
    name: CI
    runs-on: "docker"
    steps:
      - uses: crabby_trade/.github/workflows/build.yml@main
