name: docks

on:
  push:
  pull_request:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  run-tests:
    uses: crabby_trade/crabby_trade/.github/workflows/build.yml@main
    steps:
      - name: build docks
        run: cargo doc --no-deps --document-private-items
