name: docks

on:
  push:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-docs:
    name: build docs
    runs-on: "docker"
    steps:
      - uses: crabby_trade/.github/workflows/build.yml@main
