name: docks

on:
  push:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-docs:
    name: docks
    runs-on: ubuntu-latest
    steps:
      - 
        name: Check out repo
        uses: actions/checkout@v3
      - 
        name: run tests
        run: make build-docs
