name: publish

on:
  push:
  pull_request:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  publish image:
    name: publish image
    runs-on: docker
    steps:
      - uses: crabby_trade/crabby_trade/.github/workflows/build.yml@main
